[package]
name = "vpb"
version = "0.1.0"
edition = "2021"

[lib]
name = "vpb"
path = "src/lib.rs"

[toolchain]
channel = "nightly"

[profile.dev]
opt-level = 0
[profile.dev.package."*"]
opt-level = 3

[dependencies]
ash = "0.37.2+1.3.238"